apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-green
  namespace: chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      version: green
  template:
    metadata:
      labels:
        app: backend
        version: green
    spec:
      containers:
      - name: chatapp-backend
        image: ankim628/chatgitbackendgcp:${IMAGE_TAG}
        ports:
        - containerPort: 5001
        env:
        - name: NODE_ENV
          value: production
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: chatapp-secrets
              key: mongodb_uri
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: chatapp-secrets
              key: jwt
        - name: PORT
          value: "5001"
