apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-blue
  namespace: chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      version: blue
  template:
    metadata:
      labels:
        app: frontend
        version: blue
    spec:
      containers:
      - name: chatapp-frontend
        image: ankim628/chatgitfrontend:03
        ports:
        - containerPort: 80
        env:
        - name: NODE_ENV
          value: production
