apiVersion: v1
kind: Secret
metadata:
  name: chatapp-secrets
  namespace: chat-app
type: Opaque
data:
  jwt: a2hxbGljcmhnbGl1aHFraHFsaWNyaGdsaXVocWx1aHJmbHVocmY=
stringData:
  mongodb_uri: ${MONGODB_URI}
